import {
  CREAM,
  FOREST,
  INK,
  RUST,
  p,
  renderInuaBizEmail,
  type InuaBizEmailOpts,
} from "@/lib/email/layout";

export type EmailCategory = "auth" | "transactional" | "ops";

export type BundledTemplate = {
  id: string;
  category: EmailCategory;
  name: string;
  subject: string;
  html: string;
  description: string;
};

type Spec = Omit<InuaBizEmailOpts, "siteUrl" | "bodyHtml"> & {
  id: string;
  category: EmailCategory;
  name: string;
  subject: string;
  description: string;
  body: string;
};

const APP = "https://app.inuabiz.co.ke";
const ADMIN = "https://admin.inuabiz.co.ke";

const SPECS: Spec[] = [
  {
    id: "welcome-trial",
    category: "auth",
    name: "Welcome — trial started",
    subject: "Your till is live — 3-day trial",
    description: "Sent after onboarding when a vendor starts the 3-day trial.",
    badge: "WELCOME",
    headlineLine1: "Your till",
    headlineLine2: "is live.",
    heroSub: "Karibu to InuaBiz, Mama Njoroge.",
    greeting: "Hello Mama Njoroge,",
    body: "Your 3-day trial is on. POS, M-Pesa reconciliation, duka debt and stock alerts are ready on this phone.",
    ctaLabel: "Open the till",
    ctaUrl: `${APP}/app`,
    noticeTitle: "DIDN'T REQUEST THIS?",
    noticeBody: "If this was not you, ignore this email or write hello@inuabiz.co.ke.",
  },
  {
    id: "invite-staff",
    category: "auth",
    name: "Invite staff",
    subject: "You're invited to the till",
    description: "Vendor admin invites a cashier by phone, and optionally emails this branded invite.",
    badge: "INVITE",
    headlineLine1: "You're invited",
    headlineLine2: "to the till.",
    heroSub: "Mama Njoroge added you as a cashier.",
    greeting: "Hello Faith Wanjiku,",
    body: "You have been invited to sell on Mama Njoroge's duka. Open the link, then sign in with the phone number on this invite.",
    ctaLabel: "Accept invite",
    ctaUrl: "{{ .ConfirmationURL }}",
    details: [
      { label: "Shop", value: "Mama Njoroge's Duka" },
      { label: "Role", value: "Cashier" },
      { label: "Invited by", value: "Mama Njoroge" },
    ],
    noticeTitle: "WRONG PERSON?",
    noticeBody: "If you do not work at this duka, ignore this email. The invite expires in 7 days.",
  },
  {
    id: "confirm-email",
    category: "auth",
    name: "Signup OTP",
    subject: "Your InuaBiz email code",
    description: "Auth confirmation after email/password sign-up. Enter the 6-digit code, then finish shop onboarding.",
    badge: "CODE",
    headlineLine1: "Your email",
    headlineLine2: "code.",
    heroSub: "Enter this 6-digit code to finish sign-up.",
    greeting: "Hello Mama Njoroge,",
    body: "This code expires in one hour. After you enter it we send you to shop setup. Your first shop starts a 3-day trial.",
    otpCode: "847291",
    ctaLabel: "I have the code",
    ctaUrl: `${APP}/signup`,
    noticeTitle: "DIDN'T CREATE AN ACCOUNT?",
    noticeBody: "If you did not sign up for InuaBiz, ignore this email. Nobody else can use the code.",
  },
  {
    id: "magic-link-admin",
    category: "auth",
    name: "Magic link — admin",
    subject: "Sign in to the InuaBiz desk",
    description: "One-time desktop link for super-admin (zack@inuabiz.co.ke).",
    badge: "ADMIN",
    badgeFill: FOREST,
    badgeText: CREAM,
    headlineLine1: "Sign in to",
    headlineLine2: "the desk.",
    heroSub: "One-time link for zack@inuabiz.co.ke",
    greeting: "Hello Zack,",
    body: "Use this link on your laptop to open the InuaBiz command centre. It expires in 15 minutes and works once.",
    ctaLabel: "Open admin",
    ctaUrl: "{{ .ConfirmationURL }}",
    details: [
      { label: "Account", value: "zack@inuabiz.co.ke" },
      { label: "Expires", value: "15 minutes" },
      { label: "Device", value: "Desktop" },
    ],
    noticeTitle: "NOT YOU?",
    noticeBody: "If you did not ask for a desktop session, ignore this email and tell the team in #ops.",
  },
  {
    id: "confirm-its-you",
    category: "auth",
    name: "Confirm it's you",
    subject: "Confirm it's you — shop impersonation",
    description: "Re-auth before impersonation or sensitive billing.",
    badge: "SECURITY",
    badgeFill: RUST,
    badgeText: CREAM,
    headlineLine1: "Confirm it's",
    headlineLine2: "you.",
    heroSub: "Someone is about to impersonate a shop.",
    greeting: "Hello Zack,",
    body: "Support asked to view Mama Njoroge's Duka as an operator. Confirm this is you before the session starts. This is logged.",
    ctaLabel: "Yes, it's me",
    ctaUrl: "{{ .ConfirmationURL }}",
    ctaFill: RUST,
    heroTone: "rust",
    details: [
      { label: "Shop", value: "Mama Njoroge's Duka" },
      { label: "Action", value: "Impersonate" },
      { label: "IP", value: "41.90.xx.xx" },
    ],
    noticeTitle: "DIDN'T ASK FOR THIS?",
    noticeBody: "Do not tap the button. Write hello@inuabiz.co.ke immediately — someone may be trying to open a shop as you.",
    noticeColor: RUST,
  },
  {
    id: "sale-receipt",
    category: "transactional",
    name: "Sale receipt",
    subject: "Receipt for KES 905 — Mama Njoroge's Duka",
    description: "POS “Send email receipt” after an M-Pesa sale.",
    badge: "RECEIPT",
    badgeFill: FOREST,
    badgeText: CREAM,
    headlineLine1: "Receipt for",
    headlineLine2: "KES 905.",
    heroSub: "Mama Njoroge's Duka · 18 Aug 2026, 16:42",
    greeting: "Hello Peter O.,",
    body: "Thank you for shopping with us. Your M-Pesa payment went through. Keep this for your records.",
    ctaLabel: "View receipt",
    ctaUrl: `${APP}/app/sales`,
    details: [
      { label: "Till", value: "Mama Njoroge's Duka" },
      { label: "Method", value: "M-Pesa" },
      { label: "Ref", value: "QJI7XK2M" },
      { label: "Items", value: "Blue Band 250g · 2kg sugar" },
    ],
    noticeTitle: "NEED A COPY?",
    noticeBody: "Electronic tax record (ETR) from this till. Keep it for your books.",
  },
  {
    id: "wholesale-invoice",
    category: "transactional",
    name: "Wholesale invoice sent",
    subject: "Invoice INV-2041 from Mama Njoroge's Duka",
    description: "Wholesale invoice emailed to a buyer (Kariobangi Wholesalers).",
    badge: "INVOICE",
    badgeFill: FOREST,
    badgeText: CREAM,
    headlineLine1: "Invoice",
    headlineLine2: "INV-2041.",
    heroSub: "Kariobangi Wholesalers · due 25 Aug",
    greeting: "Hello Kariobangi Wholesalers,",
    body: "Mama Njoroge's Duka has sent you a wholesale invoice. Pay by M-Pesa or on delivery as agreed. A PDF copy is attached when we send live mail.",
    ctaLabel: "Open invoice",
    ctaUrl: `${APP}/app/invoices`,
    details: [
      { label: "From", value: "Mama Njoroge's Duka" },
      { label: "Amount", value: "KES 12,400" },
      { label: "Due", value: "25 Aug 2026" },
      { label: "Terms", value: "Net 7" },
    ],
    noticeTitle: "NOT YOUR ORDER?",
    noticeBody: "Reply to this email or call the duka before the due date so we can void it.",
  },
  {
    id: "invoice-overdue",
    category: "transactional",
    name: "Invoice overdue",
    subject: "INV-2041 is overdue — KES 12,400",
    description: "Net-7 invoice past due; keep the credit line open.",
    badge: "OVERDUE",
    badgeFill: RUST,
    badgeText: CREAM,
    headlineLine1: "INV-2041",
    headlineLine2: "is overdue.",
    heroSub: "KES 12,400 · 3 days past due",
    greeting: "Hello Kariobangi Wholesalers,",
    body: "This invoice is now 3 days past the due date. Please settle so we can keep your credit line open for the next delivery.",
    ctaLabel: "Pay now",
    ctaUrl: `${APP}/app/invoices`,
    ctaFill: RUST,
    heroTone: "rust",
    details: [
      { label: "Invoice", value: "INV-2041" },
      { label: "Amount", value: "KES 12,400" },
      { label: "Was due", value: "25 Aug 2026" },
      { label: "Shop", value: "Mama Njoroge's Duka" },
    ],
    noticeTitle: "ALREADY PAID?",
    noticeBody: "If you have paid, send the M-Pesa code to the duka so they can mark it received.",
    noticeColor: RUST,
  },
  {
    id: "credit-reminder",
    category: "transactional",
    name: "Credit reminder",
    subject: "Ali Hassan still owes KES 760",
    description: "Duka debt nudge from the credit book.",
    badge: "CREDIT",
    headlineLine1: "Ali Hassan",
    headlineLine2: "owes KES 760.",
    heroSub: "Duka debt · 5 days on the book",
    greeting: "Hello Mama Njoroge,",
    body: "A gentle nudge you asked us to send. Ali Hassan still has KES 760 on credit from last Thursday's sale. You can mark it paid from the till when he settles.",
    ctaLabel: "Open credit book",
    ctaUrl: `${APP}/app/credit`,
    details: [
      { label: "Customer", value: "Ali Hassan" },
      { label: "Balance", value: "KES 760" },
      { label: "Since", value: "14 Aug 2026" },
      { label: "Last sale", value: "Sugar 2kg + cooking oil" },
    ],
    noticeTitle: "CUSTOMER COPY",
    noticeBody: "This reminder was also sent to the number on Ali's profile if one is saved.",
  },
  {
    id: "low-stock",
    category: "transactional",
    name: "Low stock",
    subject: "Blue Band 250g is running out",
    description: "Inventory dropped below reorder point.",
    badge: "STOCK",
    badgeFill: RUST,
    badgeText: CREAM,
    headlineLine1: "Blue Band 250g",
    headlineLine2: "is running out.",
    heroSub: "4 tins left · reorder point 12",
    greeting: "Hello Mama Njoroge,",
    body: "Blue Band 250g has dropped below your reorder point. Restock before the weekend rush so you do not lose sales.",
    ctaLabel: "Open inventory",
    ctaUrl: `${APP}/app/inventory`,
    ctaFill: RUST,
    heroTone: "rust",
    details: [
      { label: "SKU", value: "BB-250" },
      { label: "On hand", value: "4" },
      { label: "Reorder at", value: "12" },
      { label: "Vendor", value: "Bidco" },
    ],
    noticeTitle: "TOO MANY ALERTS?",
    noticeBody: "Adjust reorder points in Inventory, or mute this product from Settings → Alerts.",
    noticeColor: RUST,
  },
  {
    id: "trial-ending",
    category: "transactional",
    name: "Trial ending",
    subject: "3 days left on your InuaBiz trial",
    description: "Trial expiry reminder before KES 3,000 STK.",
    badge: "TRIAL",
    headlineLine1: "3 days left",
    headlineLine2: "on trial.",
    heroSub: "Then KES 3,000 / month to keep the till",
    greeting: "Hello Mama Njoroge,",
    body: "Your 3-day trial is ending. Subscribe with M-Pesa so POS, receipts and stock alerts stay on. Nothing is deleted if you pause — you just cannot sell until you renew.",
    ctaLabel: "Subscribe — KES 3,000",
    ctaUrl: `${APP}/app/billing`,
    details: [
      { label: "Plan", value: "Duka · monthly" },
      { label: "Amount", value: "KES 3,000" },
      { label: "Trial ends", value: "21 Aug 2026" },
    ],
    noticeTitle: "NEED MORE TIME?",
    noticeBody: "Reply to hello@inuabiz.co.ke if a delivery delayed you. We can extend a trial once.",
  },
  {
    id: "subscription-paid",
    category: "transactional",
    name: "Subscription paid",
    subject: "You're covered this month — KES 3,000",
    description: "M-Pesa subscription receipt.",
    badge: "PAID",
    badgeFill: FOREST,
    badgeText: CREAM,
    headlineLine1: "You're covered",
    headlineLine2: "this month.",
    heroSub: "KES 3,000 received · M-Pesa",
    greeting: "Hello Mama Njoroge,",
    body: "Asante. Your InuaBiz subscription is active until 18 Sep 2026. This is your receipt for the shop.",
    ctaLabel: "View billing",
    ctaUrl: `${APP}/app/billing`,
    details: [
      { label: "Amount", value: "KES 3,000" },
      { label: "Method", value: "M-Pesa" },
      { label: "Ref", value: "THX9K2LP" },
      { label: "Next bill", value: "18 Sep 2026" },
    ],
    noticeTitle: "NOT YOUR PAYMENT?",
    noticeBody: "If this STK was not you, write hello@inuabiz.co.ke with the M-Pesa code.",
  },
  {
    id: "payment-stk-failed",
    category: "transactional",
    name: "Payment / STK failed",
    subject: "STK did not go through — KES 3,000",
    description: "Cancelled or timed-out M-Pesa prompt.",
    badge: "FAILED",
    badgeFill: RUST,
    badgeText: CREAM,
    headlineLine1: "STK did not",
    headlineLine2: "go through.",
    heroSub: "KES 3,000 · subscription attempt",
    greeting: "Hello Mama Njoroge,",
    body: "The M-Pesa prompt on 0712 345 678 was cancelled or timed out. Your till stays on trial until 21 Aug. Try again from Billing when you are next to the phone.",
    ctaLabel: "Retry payment",
    ctaUrl: `${APP}/app/billing`,
    ctaFill: RUST,
    heroTone: "rust",
    details: [
      { label: "Amount", value: "KES 3,000" },
      { label: "Phone", value: "0712 345 678" },
      { label: "Reason", value: "User cancelled" },
      { label: "Time", value: "18 Aug 2026, 09:14" },
    ],
    noticeTitle: "MONEY LEFT YOUR PHONE?",
    noticeBody: "If you were charged but we show failed, send the M-Pesa SMS to hello@inuabiz.co.ke and we will match it.",
    noticeColor: RUST,
  },
  {
    id: "daily-summary",
    category: "ops",
    name: "Daily summary",
    subject: "Saturday till: KES 18,600 · 34 sales",
    description: "End-of-day email if the vendor opted in under Settings → Alerts.",
    badge: "SUMMARY",
    headlineLine1: "Saturday",
    headlineLine2: "KES 18,600.",
    heroSub: "34 sales · Mama Njoroge's Duka",
    greeting: "Hello Mama Njoroge,",
    body: "Here is yesterday's till. M-Pesa matched 31 of 34 sales. Three cash sales are waiting for you to confirm in reconciliation.",
    ctaLabel: "Open the day",
    ctaUrl: `${APP}/app/sales`,
    details: [
      { label: "Sales", value: "KES 18,600" },
      { label: "Transactions", value: "34" },
      { label: "M-Pesa", value: "KES 16,240" },
      { label: "Credit given", value: "KES 760" },
      { label: "Low stock", value: "Blue Band 250g" },
    ],
    noticeTitle: "UNSUBSCRIBE",
    noticeBody: "Turn off daily email in Settings → Alerts. You will still get receipts and stock warnings.",
  },
  {
    id: "broadcast-maintenance",
    category: "ops",
    name: "Broadcast — maintenance",
    subject: "Till pause tonight · 02:00–04:00 EAT",
    description: "Admin broadcast with banner + email (banner_email channel).",
    badge: "NOTICE",
    badgeFill: INK,
    badgeText: CREAM,
    headlineLine1: "Till pause",
    headlineLine2: "tonight.",
    heroSub: "Sunday 02:00–04:00 EAT · M-Pesa stays up",
    greeting: "Hello Mama Njoroge,",
    body: "We will take InuaBiz offline for a short database upgrade. You can still accept M-Pesa on the till number. Sales will sync when we are back.",
    ctaLabel: "Status page",
    ctaUrl: `${APP}/maintenance`,
    ctaFill: INK,
    details: [
      { label: "Window", value: "19 Aug 02:00–04:00 EAT" },
      { label: "What breaks", value: "App + admin" },
      { label: "What works", value: "M-Pesa STK on till" },
    ],
    noticeTitle: "NEED THE TILL NOW?",
    noticeBody: "Write hello@inuabiz.co.ke if you must sell through the night and we will warn you before we start.",
  },
  {
    id: "contact-ack",
    category: "ops",
    name: "Contact form ack",
    subject: "We got your note — InuaBiz",
    description: "Acknowledgement from hello@inuabiz.co.ke / website contact.",
    badge: "HELLO",
    headlineLine1: "We got",
    headlineLine2: "your note.",
    heroSub: "hello@inuabiz.co.ke · usually same day",
    greeting: "Hello James Mwangi,",
    body: "Asante for writing from the website. A person on the InuaBiz team will reply to this address. For till emergencies, WhatsApp the number on inuabiz.co.ke.",
    ctaLabel: "Visit help",
    ctaUrl: `${APP}/contact`,
    details: [
      { label: "Topic", value: "Wholesale invoices" },
      { label: "Ref", value: "TKT-1184" },
    ],
    noticeTitle: "THIS IS AN ACKNOWLEDGEMENT",
    noticeBody: "Do not reply with OTP codes or M-Pesa PINs. We will never ask for them by email.",
  },
  {
    id: "contact-inbound",
    category: "ops",
    name: "Contact inbound — admin",
    subject: "New contact: Mama Njoroge",
    description: "Email to ops when someone submits /contact. Reply-To is the visitor.",
    badge: "INBOX",
    badgeFill: RUST,
    badgeText: CREAM,
    headlineLine1: "New website",
    headlineLine2: "contact.",
    heroSub: "Open the admin inbox to reply.",
    greeting: "Hello team,",
    body: "Mama Njoroge wrote from the website. Reply to the visitor from this thread — Reply-To is set to their address.",
    ctaLabel: "Open inbox",
    ctaUrl: `${ADMIN}/admin/inbox`,
    ctaFill: RUST,
    heroTone: "rust",
    details: [
      { label: "Topic", value: "Book a demo" },
      { label: "Email", value: "njoroge@example.com" },
      { label: "Phone", value: "0712 345 678" },
    ],
    noticeTitle: "REPLY FROM YOUR INBOX",
    noticeBody: "This copy is for the InuaBiz team. The visitor already got a separate acknowledgement.",
    noticeColor: RUST,
  },
  {
    id: "newsletter-welcome",
    category: "ops",
    name: "Newsletter welcome",
    subject: "You're on the InuaBiz list",
    description: "Confirmation after footer newsletter subscribe.",
    badge: "LIST",
    headlineLine1: "You're on",
    headlineLine2: "the list.",
    heroSub: "Till news in your inbox.",
    greeting: "Hello,",
    body: "Asante. We will send till notes, pricing changes and Nairobi shop stories to this address. You can leave the list any time — write hello@inuabiz.co.ke.",
    ctaLabel: "Open InuaBiz",
    ctaUrl: "https://www.inuabiz.co.ke",
    noticeTitle: "NOT YOU?",
    noticeBody: "If you did not subscribe, ignore this email or write hello@inuabiz.co.ke.",
  },
  {
    id: "unclaimed-payment",
    category: "transactional",
    name: "Unclaimed payment",
    subject: "KES 1,200 unmatched on your till",
    description: "M-Pesa hit the till with no open sale.",
    badge: "OPS",
    badgeFill: RUST,
    badgeText: CREAM,
    headlineLine1: "KES 1,200",
    headlineLine2: "unmatched.",
    heroSub: "M-Pesa hit the till with no open sale",
    greeting: "Hello Mama Njoroge,",
    body: "Someone paid KES 1,200 to your till but it did not match a sale. Claim it from Unclaimed payments or refund if you do not recognise the name.",
    ctaLabel: "Claim payment",
    ctaUrl: `${ADMIN}/admin/unclaimed`,
    ctaFill: RUST,
    heroTone: "rust",
    details: [
      { label: "Amount", value: "KES 1,200" },
      { label: "Payer", value: "J. Kamau" },
      { label: "Time", value: "18 Aug 2026, 11:03" },
      { label: "Till", value: "Mama Njoroge's Duka" },
    ],
    noticeTitle: "UNKNOWN PAYER?",
    noticeBody: "If the name is not a customer, do not allocate it to a random sale. Use refund from the ops screen.",
    noticeColor: RUST,
  },
  {
    id: "password-reset",
    category: "auth",
    name: "Password reset",
    subject: "Reset your InuaBiz password",
    description: "Auth recovery for email/password vendors. Link works once.",
    badge: "RESET",
    badgeFill: RUST,
    badgeText: CREAM,
    headlineLine1: "Reset your",
    headlineLine2: "password.",
    heroSub: "This link works once and expires in 15 minutes.",
    greeting: "Hello Mama Njoroge,",
    body: "Someone asked to reset the password for this InuaBiz account. If it was you, tap the button. If not, ignore this email — your password stays the same.",
    ctaLabel: "Reset password",
    ctaUrl: "{{ .ConfirmationURL }}",
    ctaFill: RUST,
    heroTone: "rust",
    noticeTitle: "DIDN'T ASK FOR THIS?",
    noticeBody: "We will never ask for your password or M-Pesa PIN by email.",
    noticeColor: RUST,
  },
  {
    id: "onboarding-incomplete",
    category: "auth",
    name: "Finish shop setup",
    subject: "Finish setting up your InuaBiz shop",
    description: "Drop-off lock: signed up but did not complete onboarding.",
    badge: "SETUP",
    headlineLine1: "Finish setting",
    headlineLine2: "up your shop.",
    heroSub: "You signed up but POS stays locked until shop setup is done.",
    greeting: "Hello Mama Njoroge,",
    body: "Sign in and finish category, location and M-Pesa destination. Your 3-day trial starts when onboarding completes.",
    ctaLabel: "Continue setup",
    ctaUrl: `${APP}/onboarding`,
    noticeTitle: "STUCK?",
    noticeBody: "Write hello@inuabiz.co.ke if you cannot get back into setup.",
  },
  {
    id: "extra-shop-paid",
    category: "transactional",
    name: "Extra shop paid",
    subject: "New shop is paid for — KES 3,000",
    description: "STK succeeded; extra shop row inserted.",
    badge: "PAID",
    badgeFill: FOREST,
    badgeText: CREAM,
    headlineLine1: "New shop is",
    headlineLine2: "paid for.",
    heroSub: "Ngara branch · KES 3,000",
    greeting: "Hello Mama Njoroge,",
    body: "Asante. The new location is now on your account. Monthly billing is KES 3,000 times the number of shops.",
    ctaLabel: "Open shops",
    ctaUrl: `${APP}/app/shops`,
    details: [
      { label: "Amount", value: "KES 3,000" },
      { label: "Method", value: "M-Pesa" },
      { label: "Shop", value: "Ngara branch" },
    ],
    noticeTitle: "NOT YOUR PAYMENT?",
    noticeBody: "If this STK was not you, write hello@inuabiz.co.ke with the M-Pesa code.",
  },
  {
    id: "extra-shop-failed",
    category: "transactional",
    name: "Extra shop STK failed",
    subject: "Extra shop PIN did not go through — KES 3,000",
    description: "Extra-shop STK cancelled or timed out; shop was not created.",
    badge: "FAILED",
    badgeFill: RUST,
    badgeText: CREAM,
    headlineLine1: "STK did not",
    headlineLine2: "go through.",
    heroSub: "KES 3,000 · extra shop",
    greeting: "Hello Mama Njoroge,",
    body: "The PIN for the extra shop did not go through. That location was not created. Try again from Shops when you are next to the phone.",
    ctaLabel: "Retry from Shops",
    ctaUrl: `${APP}/app/shops`,
    ctaFill: RUST,
    heroTone: "rust",
    details: [
      { label: "Amount", value: "KES 3,000" },
      { label: "Reason", value: "User cancelled" },
    ],
    noticeTitle: "MONEY LEFT YOUR PHONE?",
    noticeBody: "If you were charged but we show failed, send the M-Pesa SMS to hello@inuabiz.co.ke and we will match it.",
    noticeColor: RUST,
  },
  {
    id: "fiscal-invoice",
    category: "transactional",
    name: "Fiscal invoice",
    subject: "Tax invoice INB-2026-0042 — Mama Njoroge's Duka",
    description: "Audit-ready INB-YYYY-NNNN invoice after a PAID/CREDIT sale.",
    badge: "INVOICE",
    badgeFill: FOREST,
    badgeText: CREAM,
    headlineLine1: "Tax invoice",
    headlineLine2: "INB-2026-0042.",
    heroSub: "Mama Njoroge's Duka · audit-ready record",
    greeting: "Hello Peter O.,",
    body: "This is your audit-ready tax invoice (ETR) from the till.",
    ctaLabel: "Open invoice",
    ctaUrl: `${APP}/app/sales`,
    details: [
      { label: "Invoice", value: "INB-2026-0042" },
      { label: "Amount", value: "KES 905" },
      { label: "VAT", value: "Rate A 16%" },
      { label: "Till", value: "Mama Njoroge's Duka" },
    ],
    noticeTitle: "KEEP FOR YOUR BOOKS",
    noticeBody: "InuaBiz generated this ETR record for your shop. It is not a KRA control-unit printout.",
  },
];

/**
 * Build the Figma-backed templates. Pass origin so preview CTAs match the running app.
 */
export function buildCommunicationTemplates(siteUrl = "{{ .SiteURL }}"): BundledTemplate[] {
  return SPECS.map((spec) => {
    const { id, category, name, subject, description, body, ...opts } = spec;
    return {
      id,
      category,
      name,
      subject,
      description,
      html: renderInuaBizEmail({
        ...opts,
        siteUrl,
        bodyHtml: p(body),
      }),
    };
  });
}

/** Bundled catalog used when `communication_templates` is empty or missing. */
export const BUNDLED_COMMUNICATION_TEMPLATES = buildCommunicationTemplates();
