/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R403RouteImport } from './routes/403'
import { Route as R404RouteImport } from './routes/404'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CompanionRouteImport } from './routes/companion'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ForDukasRouteImport } from './routes/for-dukas'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as KaribuRouteImport } from './routes/karibu'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as VerifyReceiptRouteImport } from './routes/verify-receipt'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAiRouteImport } from './routes/admin.ai'
import { Route as AdminBroadcastsRouteImport } from './routes/admin.broadcasts'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminCommunicationsRouteImport } from './routes/admin.communications'
import { Route as AdminFxRouteImport } from './routes/admin.fx'
import { Route as AdminHealthRouteImport } from './routes/admin.health'
import { Route as AdminInboxRouteImport } from './routes/admin.inbox'
import { Route as AdminIntelligenceRouteImport } from './routes/admin.intelligence'
import { Route as AdminMapRouteImport } from './routes/admin.map'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminPlansRouteImport } from './routes/admin.plans'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminTicketsRouteImport } from './routes/admin.tickets'
import { Route as AdminUnclaimedRouteImport } from './routes/admin.unclaimed'
import { Route as AdminVendorsRouteImport } from './routes/admin.vendors'
import { Route as ApiSentryExampleRouteImport } from './routes/api.sentry-example'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppBillingRouteImport } from './routes/app.billing'
import { Route as AppCreditRouteImport } from './routes/app.credit'
import { Route as AppCustomersRouteImport } from './routes/app.customers'
import { Route as AppExpiryRouteImport } from './routes/app.expiry'
import { Route as AppFloorRouteImport } from './routes/app.floor'
import { Route as AppImportRouteImport } from './routes/app.import'
import { Route as AppInsightsRouteImport } from './routes/app.insights'
import { Route as AppInventoryRouteImport } from './routes/app.inventory'
import { Route as AppInvoicesRouteImport } from './routes/app.invoices'
import { Route as AppKitchenRouteImport } from './routes/app.kitchen'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppPosRouteImport } from './routes/app.pos'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppSalesRouteImport } from './routes/app.sales'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppShopsRouteImport } from './routes/app.shops'
import { Route as AppSupportRouteImport } from './routes/app.support'
import { Route as AppTicketsRouteImport } from './routes/app.tickets'
import { Route as AdminTenantsTenantIdRouteImport } from './routes/admin.tenants_.$tenantId'
import { Route as AppCustomersCustomerIdRouteImport } from './routes/app.customers_.$customerId'
import { Route as AppInventoryProductIdRouteImport } from './routes/app.inventory_.$productId'
import { Route as AppInventoryNewRouteImport } from './routes/app.inventory_.new'
import { Route as AppPosSuccessRouteImport } from './routes/app.pos_.success'
import { Route as AppSalesSaleIdRouteImport } from './routes/app.sales_.$saleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanionRoute = CompanionRouteImport.update({
  id: '/companion',
  path: '/companion',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ForDukasRoute = ForDukasRouteImport.update({
  id: '/for-dukas',
  path: '/for-dukas',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const KaribuRoute = KaribuRouteImport.update({
  id: '/karibu',
  path: '/karibu',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyReceiptRoute = VerifyReceiptRouteImport.update({
  id: '/verify-receipt',
  path: '/verify-receipt',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiRoute = AdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBroadcastsRoute = AdminBroadcastsRouteImport.update({
  id: '/broadcasts',
  path: '/broadcasts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommunicationsRoute = AdminCommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFxRoute = AdminFxRouteImport.update({
  id: '/fx',
  path: '/fx',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHealthRoute = AdminHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInboxRoute = AdminInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntelligenceRoute = AdminIntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMapRoute = AdminMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTicketsRoute = AdminTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUnclaimedRoute = AdminUnclaimedRouteImport.update({
  id: '/unclaimed',
  path: '/unclaimed',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVendorsRoute = AdminVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AdminRoute,
} as any)
const ApiSentryExampleRoute = ApiSentryExampleRouteImport.update({
  id: '/api/sentry-example',
  path: '/api/sentry-example',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppCreditRoute = AppCreditRouteImport.update({
  id: '/credit',
  path: '/credit',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppExpiryRoute = AppExpiryRouteImport.update({
  id: '/expiry',
  path: '/expiry',
  getParentRoute: () => AppRoute,
} as any)
const AppFloorRoute = AppFloorRouteImport.update({
  id: '/floor',
  path: '/floor',
  getParentRoute: () => AppRoute,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppKitchenRoute = AppKitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppPosRoute = AppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppShopsRoute = AppShopsRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppTicketsRoute = AppTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AppRoute,
} as any)
const AdminTenantsTenantIdRoute = AdminTenantsTenantIdRouteImport.update({
  id: '/tenants_/$tenantId',
  path: '/tenants/$tenantId',
  getParentRoute: () => AdminRoute,
} as any)
const AppCustomersCustomerIdRoute = AppCustomersCustomerIdRouteImport.update({
  id: '/customers_/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryProductIdRoute = AppInventoryProductIdRouteImport.update({
  id: '/inventory_/$productId',
  path: '/inventory/$productId',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryNewRoute = AppInventoryNewRouteImport.update({
  id: '/inventory_/new',
  path: '/inventory/new',
  getParentRoute: () => AppRoute,
} as any)
const AppPosSuccessRoute = AppPosSuccessRouteImport.update({
  id: '/pos_/success',
  path: '/pos/success',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesSaleIdRoute = AppSalesSaleIdRouteImport.update({
  id: '/sales_/$saleId',
  path: '/sales/$saleId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/companion': typeof CompanionRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/for-dukas': typeof ForDukasRoute
  '/how-it-works': typeof HowItWorksRoute
  '/karibu': typeof KaribuRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/verify-receipt': typeof VerifyReceiptRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/broadcasts': typeof AdminBroadcastsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/communications': typeof AdminCommunicationsRoute
  '/admin/fx': typeof AdminFxRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/intelligence': typeof AdminIntelligenceRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/unclaimed': typeof AdminUnclaimedRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/api/sentry-example': typeof ApiSentryExampleRoute
  '/app/billing': typeof AppBillingRoute
  '/app/credit': typeof AppCreditRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/expiry': typeof AppExpiryRoute
  '/app/floor': typeof AppFloorRoute
  '/app/import': typeof AppImportRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/kitchen': typeof AppKitchenRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/pos': typeof AppPosRoute
  '/app/profile': typeof AppProfileRoute
  '/app/sales': typeof AppSalesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shops': typeof AppShopsRoute
  '/app/support': typeof AppSupportRoute
  '/app/tickets': typeof AppTicketsRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/tenants/$tenantId': typeof AdminTenantsTenantIdRoute
  '/app/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/app/inventory/$productId': typeof AppInventoryProductIdRoute
  '/app/inventory/new': typeof AppInventoryNewRoute
  '/app/pos/success': typeof AppPosSuccessRoute
  '/app/sales/$saleId': typeof AppSalesSaleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/auth': typeof AuthRoute
  '/companion': typeof CompanionRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/for-dukas': typeof ForDukasRoute
  '/how-it-works': typeof HowItWorksRoute
  '/karibu': typeof KaribuRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/verify-receipt': typeof VerifyReceiptRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/broadcasts': typeof AdminBroadcastsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/communications': typeof AdminCommunicationsRoute
  '/admin/fx': typeof AdminFxRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/intelligence': typeof AdminIntelligenceRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/unclaimed': typeof AdminUnclaimedRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/api/sentry-example': typeof ApiSentryExampleRoute
  '/app/billing': typeof AppBillingRoute
  '/app/credit': typeof AppCreditRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/expiry': typeof AppExpiryRoute
  '/app/floor': typeof AppFloorRoute
  '/app/import': typeof AppImportRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/kitchen': typeof AppKitchenRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/pos': typeof AppPosRoute
  '/app/profile': typeof AppProfileRoute
  '/app/sales': typeof AppSalesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shops': typeof AppShopsRoute
  '/app/support': typeof AppSupportRoute
  '/app/tickets': typeof AppTicketsRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/admin/tenants/$tenantId': typeof AdminTenantsTenantIdRoute
  '/app/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/app/inventory/$productId': typeof AppInventoryProductIdRoute
  '/app/inventory/new': typeof AppInventoryNewRoute
  '/app/pos/success': typeof AppPosSuccessRoute
  '/app/sales/$saleId': typeof AppSalesSaleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/companion': typeof CompanionRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/for-dukas': typeof ForDukasRoute
  '/how-it-works': typeof HowItWorksRoute
  '/karibu': typeof KaribuRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/verify-receipt': typeof VerifyReceiptRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/broadcasts': typeof AdminBroadcastsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/communications': typeof AdminCommunicationsRoute
  '/admin/fx': typeof AdminFxRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/intelligence': typeof AdminIntelligenceRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/unclaimed': typeof AdminUnclaimedRoute
  '/admin/vendors': typeof AdminVendorsRoute
  '/api/sentry-example': typeof ApiSentryExampleRoute
  '/app/billing': typeof AppBillingRoute
  '/app/credit': typeof AppCreditRoute
  '/app/customers': typeof AppCustomersRoute
  '/app/expiry': typeof AppExpiryRoute
  '/app/floor': typeof AppFloorRoute
  '/app/import': typeof AppImportRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/kitchen': typeof AppKitchenRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/pos': typeof AppPosRoute
  '/app/profile': typeof AppProfileRoute
  '/app/sales': typeof AppSalesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shops': typeof AppShopsRoute
  '/app/support': typeof AppSupportRoute
  '/app/tickets': typeof AppTicketsRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/tenants_/$tenantId': typeof AdminTenantsTenantIdRoute
  '/app/customers_/$customerId': typeof AppCustomersCustomerIdRoute
  '/app/inventory_/$productId': typeof AppInventoryProductIdRoute
  '/app/inventory_/new': typeof AppInventoryNewRoute
  '/app/pos_/success': typeof AppPosSuccessRoute
  '/app/sales_/$saleId': typeof AppSalesSaleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/403'
    | '/404'
    | '/admin'
    | '/app'
    | '/auth'
    | '/companion'
    | '/contact'
    | '/features'
    | '/for-dukas'
    | '/how-it-works'
    | '/karibu'
    | '/login'
    | '/maintenance'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/verify'
    | '/verify-receipt'
    | '/admin/ai'
    | '/admin/broadcasts'
    | '/admin/categories'
    | '/admin/communications'
    | '/admin/fx'
    | '/admin/health'
    | '/admin/inbox'
    | '/admin/intelligence'
    | '/admin/map'
    | '/admin/notifications'
    | '/admin/plans'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/tickets'
    | '/admin/unclaimed'
    | '/admin/vendors'
    | '/api/sentry-example'
    | '/app/billing'
    | '/app/credit'
    | '/app/customers'
    | '/app/expiry'
    | '/app/floor'
    | '/app/import'
    | '/app/insights'
    | '/app/inventory'
    | '/app/invoices'
    | '/app/kitchen'
    | '/app/notifications'
    | '/app/pos'
    | '/app/profile'
    | '/app/sales'
    | '/app/settings'
    | '/app/shops'
    | '/app/support'
    | '/app/tickets'
    | '/admin/'
    | '/app/'
    | '/admin/tenants/$tenantId'
    | '/app/customers/$customerId'
    | '/app/inventory/$productId'
    | '/app/inventory/new'
    | '/app/pos/success'
    | '/app/sales/$saleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | '/404'
    | '/auth'
    | '/companion'
    | '/contact'
    | '/features'
    | '/for-dukas'
    | '/how-it-works'
    | '/karibu'
    | '/login'
    | '/maintenance'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/verify'
    | '/verify-receipt'
    | '/admin/ai'
    | '/admin/broadcasts'
    | '/admin/categories'
    | '/admin/communications'
    | '/admin/fx'
    | '/admin/health'
    | '/admin/inbox'
    | '/admin/intelligence'
    | '/admin/map'
    | '/admin/notifications'
    | '/admin/plans'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/tickets'
    | '/admin/unclaimed'
    | '/admin/vendors'
    | '/api/sentry-example'
    | '/app/billing'
    | '/app/credit'
    | '/app/customers'
    | '/app/expiry'
    | '/app/floor'
    | '/app/import'
    | '/app/insights'
    | '/app/inventory'
    | '/app/invoices'
    | '/app/kitchen'
    | '/app/notifications'
    | '/app/pos'
    | '/app/profile'
    | '/app/sales'
    | '/app/settings'
    | '/app/shops'
    | '/app/support'
    | '/app/tickets'
    | '/admin'
    | '/app'
    | '/admin/tenants/$tenantId'
    | '/app/customers/$customerId'
    | '/app/inventory/$productId'
    | '/app/inventory/new'
    | '/app/pos/success'
    | '/app/sales/$saleId'
  id:
    | '__root__'
    | '/'
    | '/403'
    | '/404'
    | '/admin'
    | '/app'
    | '/auth'
    | '/companion'
    | '/contact'
    | '/features'
    | '/for-dukas'
    | '/how-it-works'
    | '/karibu'
    | '/login'
    | '/maintenance'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/verify'
    | '/verify-receipt'
    | '/admin/ai'
    | '/admin/broadcasts'
    | '/admin/categories'
    | '/admin/communications'
    | '/admin/fx'
    | '/admin/health'
    | '/admin/inbox'
    | '/admin/intelligence'
    | '/admin/map'
    | '/admin/notifications'
    | '/admin/plans'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/tickets'
    | '/admin/unclaimed'
    | '/admin/vendors'
    | '/api/sentry-example'
    | '/app/billing'
    | '/app/credit'
    | '/app/customers'
    | '/app/expiry'
    | '/app/floor'
    | '/app/import'
    | '/app/insights'
    | '/app/inventory'
    | '/app/invoices'
    | '/app/kitchen'
    | '/app/notifications'
    | '/app/pos'
    | '/app/profile'
    | '/app/sales'
    | '/app/settings'
    | '/app/shops'
    | '/app/support'
    | '/app/tickets'
    | '/admin/'
    | '/app/'
    | '/admin/tenants_/$tenantId'
    | '/app/customers_/$customerId'
    | '/app/inventory_/$productId'
    | '/app/inventory_/new'
    | '/app/pos_/success'
    | '/app/sales_/$saleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R403Route: typeof R403Route
  R404Route: typeof R404Route
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  CompanionRoute: typeof CompanionRoute
  ContactRoute: typeof ContactRoute
  FeaturesRoute: typeof FeaturesRoute
  ForDukasRoute: typeof ForDukasRoute
  HowItWorksRoute: typeof HowItWorksRoute
  KaribuRoute: typeof KaribuRoute
  LoginRoute: typeof LoginRoute
  MaintenanceRoute: typeof MaintenanceRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  VerifyRoute: typeof VerifyRoute
  VerifyReceiptRoute: typeof VerifyReceiptRoute
  ApiSentryExampleRoute: typeof ApiSentryExampleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companion': {
      id: '/companion'
      path: '/companion'
      fullPath: '/companion'
      preLoaderRoute: typeof CompanionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-dukas': {
      id: '/for-dukas'
      path: '/for-dukas'
      fullPath: '/for-dukas'
      preLoaderRoute: typeof ForDukasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karibu': {
      id: '/karibu'
      path: '/karibu'
      fullPath: '/karibu'
      preLoaderRoute: typeof KaribuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-receipt': {
      id: '/verify-receipt'
      path: '/verify-receipt'
      fullPath: '/verify-receipt'
      preLoaderRoute: typeof VerifyReceiptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai': {
      id: '/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AdminAiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/broadcasts': {
      id: '/admin/broadcasts'
      path: '/broadcasts'
      fullPath: '/admin/broadcasts'
      preLoaderRoute: typeof AdminBroadcastsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/communications': {
      id: '/admin/communications'
      path: '/communications'
      fullPath: '/admin/communications'
      preLoaderRoute: typeof AdminCommunicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fx': {
      id: '/admin/fx'
      path: '/fx'
      fullPath: '/admin/fx'
      preLoaderRoute: typeof AdminFxRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/health': {
      id: '/admin/health'
      path: '/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AdminHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inbox': {
      id: '/admin/inbox'
      path: '/inbox'
      fullPath: '/admin/inbox'
      preLoaderRoute: typeof AdminInboxRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/intelligence': {
      id: '/admin/intelligence'
      path: '/intelligence'
      fullPath: '/admin/intelligence'
      preLoaderRoute: typeof AdminIntelligenceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/map': {
      id: '/admin/map'
      path: '/map'
      fullPath: '/admin/map'
      preLoaderRoute: typeof AdminMapRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tickets': {
      id: '/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AdminTicketsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/unclaimed': {
      id: '/admin/unclaimed'
      path: '/unclaimed'
      fullPath: '/admin/unclaimed'
      preLoaderRoute: typeof AdminUnclaimedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vendors': {
      id: '/admin/vendors'
      path: '/vendors'
      fullPath: '/admin/vendors'
      preLoaderRoute: typeof AdminVendorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/sentry-example': {
      id: '/api/sentry-example'
      path: '/api/sentry-example'
      fullPath: '/api/sentry-example'
      preLoaderRoute: typeof ApiSentryExampleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/credit': {
      id: '/app/credit'
      path: '/credit'
      fullPath: '/app/credit'
      preLoaderRoute: typeof AppCreditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customers': {
      id: '/app/customers'
      path: '/customers'
      fullPath: '/app/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/expiry': {
      id: '/app/expiry'
      path: '/expiry'
      fullPath: '/app/expiry'
      preLoaderRoute: typeof AppExpiryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/floor': {
      id: '/app/floor'
      path: '/floor'
      fullPath: '/app/floor'
      preLoaderRoute: typeof AppFloorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/import': {
      id: '/app/import'
      path: '/import'
      fullPath: '/app/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/insights': {
      id: '/app/insights'
      path: '/insights'
      fullPath: '/app/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory': {
      id: '/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invoices': {
      id: '/app/invoices'
      path: '/invoices'
      fullPath: '/app/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/kitchen': {
      id: '/app/kitchen'
      path: '/kitchen'
      fullPath: '/app/kitchen'
      preLoaderRoute: typeof AppKitchenRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pos': {
      id: '/app/pos'
      path: '/pos'
      fullPath: '/app/pos'
      preLoaderRoute: typeof AppPosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sales': {
      id: '/app/sales'
      path: '/sales'
      fullPath: '/app/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/shops': {
      id: '/app/shops'
      path: '/shops'
      fullPath: '/app/shops'
      preLoaderRoute: typeof AppShopsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/support': {
      id: '/app/support'
      path: '/support'
      fullPath: '/app/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tickets': {
      id: '/app/tickets'
      path: '/tickets'
      fullPath: '/app/tickets'
      preLoaderRoute: typeof AppTicketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/tenants_/$tenantId': {
      id: '/admin/tenants_/$tenantId'
      path: '/tenants/$tenantId'
      fullPath: '/admin/tenants/$tenantId'
      preLoaderRoute: typeof AdminTenantsTenantIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/customers_/$customerId': {
      id: '/app/customers_/$customerId'
      path: '/customers/$customerId'
      fullPath: '/app/customers/$customerId'
      preLoaderRoute: typeof AppCustomersCustomerIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory_/$productId': {
      id: '/app/inventory_/$productId'
      path: '/inventory/$productId'
      fullPath: '/app/inventory/$productId'
      preLoaderRoute: typeof AppInventoryProductIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory_/new': {
      id: '/app/inventory_/new'
      path: '/inventory/new'
      fullPath: '/app/inventory/new'
      preLoaderRoute: typeof AppInventoryNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pos_/success': {
      id: '/app/pos_/success'
      path: '/pos/success'
      fullPath: '/app/pos/success'
      preLoaderRoute: typeof AppPosSuccessRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sales_/$saleId': {
      id: '/app/sales_/$saleId'
      path: '/sales/$saleId'
      fullPath: '/app/sales/$saleId'
      preLoaderRoute: typeof AppSalesSaleIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAiRoute: typeof AdminAiRoute
  AdminBroadcastsRoute: typeof AdminBroadcastsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCommunicationsRoute: typeof AdminCommunicationsRoute
  AdminFxRoute: typeof AdminFxRoute
  AdminHealthRoute: typeof AdminHealthRoute
  AdminInboxRoute: typeof AdminInboxRoute
  AdminIntelligenceRoute: typeof AdminIntelligenceRoute
  AdminMapRoute: typeof AdminMapRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminTicketsRoute: typeof AdminTicketsRoute
  AdminUnclaimedRoute: typeof AdminUnclaimedRoute
  AdminVendorsRoute: typeof AdminVendorsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminTenantsTenantIdRoute: typeof AdminTenantsTenantIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiRoute: AdminAiRoute,
  AdminBroadcastsRoute: AdminBroadcastsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCommunicationsRoute: AdminCommunicationsRoute,
  AdminFxRoute: AdminFxRoute,
  AdminHealthRoute: AdminHealthRoute,
  AdminInboxRoute: AdminInboxRoute,
  AdminIntelligenceRoute: AdminIntelligenceRoute,
  AdminMapRoute: AdminMapRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminTicketsRoute: AdminTicketsRoute,
  AdminUnclaimedRoute: AdminUnclaimedRoute,
  AdminVendorsRoute: AdminVendorsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminTenantsTenantIdRoute: AdminTenantsTenantIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppBillingRoute: typeof AppBillingRoute
  AppCreditRoute: typeof AppCreditRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppExpiryRoute: typeof AppExpiryRoute
  AppFloorRoute: typeof AppFloorRoute
  AppImportRoute: typeof AppImportRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppKitchenRoute: typeof AppKitchenRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPosRoute: typeof AppPosRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSalesRoute: typeof AppSalesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppShopsRoute: typeof AppShopsRoute
  AppSupportRoute: typeof AppSupportRoute
  AppTicketsRoute: typeof AppTicketsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCustomersCustomerIdRoute: typeof AppCustomersCustomerIdRoute
  AppInventoryProductIdRoute: typeof AppInventoryProductIdRoute
  AppInventoryNewRoute: typeof AppInventoryNewRoute
  AppPosSuccessRoute: typeof AppPosSuccessRoute
  AppSalesSaleIdRoute: typeof AppSalesSaleIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBillingRoute: AppBillingRoute,
  AppCreditRoute: AppCreditRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppExpiryRoute: AppExpiryRoute,
  AppFloorRoute: AppFloorRoute,
  AppImportRoute: AppImportRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppKitchenRoute: AppKitchenRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPosRoute: AppPosRoute,
  AppProfileRoute: AppProfileRoute,
  AppSalesRoute: AppSalesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppShopsRoute: AppShopsRoute,
  AppSupportRoute: AppSupportRoute,
  AppTicketsRoute: AppTicketsRoute,
  AppIndexRoute: AppIndexRoute,
  AppCustomersCustomerIdRoute: AppCustomersCustomerIdRoute,
  AppInventoryProductIdRoute: AppInventoryProductIdRoute,
  AppInventoryNewRoute: AppInventoryNewRoute,
  AppPosSuccessRoute: AppPosSuccessRoute,
  AppSalesSaleIdRoute: AppSalesSaleIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R403Route: R403Route,
  R404Route: R404Route,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  CompanionRoute: CompanionRoute,
  ContactRoute: ContactRoute,
  FeaturesRoute: FeaturesRoute,
  ForDukasRoute: ForDukasRoute,
  HowItWorksRoute: HowItWorksRoute,
  KaribuRoute: KaribuRoute,
  LoginRoute: LoginRoute,
  MaintenanceRoute: MaintenanceRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  VerifyRoute: VerifyRoute,
  VerifyReceiptRoute: VerifyReceiptRoute,
  ApiSentryExampleRoute: ApiSentryExampleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
